### ISSUE TITLE
Net::HTTP handles URIs and Strings differently

### ISSUE THREAD

**Issue by frrisus** [akamai-open/AkamaiOPEN-edgegrid-ruby#11]
There's a bit of a tricky issue with how Net::HTTP handles strings and URIs. If you pass it a string, as the example does:

`request = Net::HTTP::Get.new(URI(baseuri + path).to_s)`

then everything works fine, because the request object has a nil ``uri`` and a valid ``path``, which the library turns into a ``URI`` inside ``make_data_to_sign``:

`url = URI(request.path)`

But if you pass it a ``URI`` object instead:

`request = Net::HTTP::Get.new(URI(baseuri + path))`

then it breaks, because now the request object has a valid ``uri`` and a ``path`` that doesn't include the entire string. The library then fails because ``request.path`` doesn't have a scheme, so the ``URI`` that's created isn't a ``URI::HTTP`` or ``URI::HTTPS``, it's a ``URI::Generic``, which doesn't respond to ``#request_uri``.

I think the right answer here is to make ``make_data_to_sign`` slightly more flexible:
`url = request.uri || URI(request.path)`
which should handle both cases.

**Comment by frrisus** [comment]
Hm, I see from writing some tests that it isn't quite this simple. Maybe the path of least resistance for now is to change the documentation to say that you have to feed ``Net::HTTP`` with a string and not a URI.

**Comment by sciffer** [comment]
On Ruby 2.4 I can say for sure it is not working, I have the same issue and I don't think I'll be able to get over it without changing the lib. If I feed Net:HTTP with string I get:
'''Failed to open TCP connection to {:address=>"xxxx-xxxxxx-xxxxxxxxxxxxxxxxxx.purge.akamaiapis.net", :port=>443}:80 (no implicit conversion of Hash into String)'''
if I feed it with URI I get:
undefined method `request_uri' for #<URI::Generic /ccu/v3/invalidate/url/staging>

The library is not working for me, maybe will work with ruby 1.9 - did not check it yet.
